# -*- coding: utf-8 -*-
"""Visualization1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NbmooyOKnulPNsvwAFxisx6cQengraIq
"""

import numpy as np
import matplotlib.pyplot as plt





#set widh of bar
BarWidth = 0.25
fig = plt.subplots(figsize = (12, 8))

# set height of bar
IT = [12,30, 1,22]
ECE = [28,6,16,5]
CSE = [29,3,24,25,17]

#set position of bar on x axis 
br1 = np.arrange(len(IT)) 
br2 = [x + barWidth for